# name: 打包gitbook项目

# on: push

# permissions:
#   contents: write
  
# jobs:
#   gitbook-build:
#     name: gitbook-build工作
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: 读取仓库内容
#       uses: actions/checkout@v4
      
#     - name: 使用 Node.js V10.24.1这个版本，高版本有问题
#       uses: actions/setup-node@v2
#       with:
#         node-version: 10.24.1
      
#     - name: 安装gitbook和相关依赖
#       run: |
#         npm install gitbook-cli -g
#         npm install gitbook-plugin-lightbox
#         gitbook install
      
#     - name: 项目打包
#       run: gitbook build
    
#     - name: 部署到 GitHub Pages
#       uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         branch: gh-pages # 分支名称
#         folder: _book #部署的目录


name: Docker一键安装脚本下载

on:
  # 手动触发
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o linux.sh "https://get.docker.com"
         mkdir shell
         cp linux.sh ./shell
         date

    - name: 连接sftp服务器
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.AB_DEV_SERVER }}
        username: ${{ secrets.AB_DEV_SERVER_USER }}
        password: ${{ secrets.AB_DEV_SERVER_PASS }}
        port: ${{ secrets.AB_DEV_SERVER_PORT }}
        uploads: |
          ./shell/ => /upload/
