name: 打包gitbook项目

on: push

jobs:
  gitbook-build:
    name: gitbook-build工作
    runs-on: ubuntu-latest
    
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
      
    - name: 使用 Node.js V10.24.1这个版本
      uses: actions/setup-node@v2
      with:
        node-version: 10.24.1
      
    - name: 安装gitbook和项目打包
      run: |
        npm install gitbook-cli -g
        npm install gitbook-plugin-lightbox
        gitbook install
        gitbook build
    